<BEGDEF><AltA><TITLE>alpha<TITLE>à<ENDDEF>
<BEGDEF><AltB><TITLE>beta<TITLE>á<ENDDEF>
<BEGDEF><AltH><TITLE>one half = 0.5<TITLE>«<ENDDEF>
<BEGDEF><AltQ><TITLE>one quarter = 0.25<TITLE>¬<ENDDEF>
<BEGDEF><AltR><TITLE>square root<TITLE>û<ENDDEF>
<BEGDEF><AltS><TITLE>square (exponent 2)<TITLE>ý<ENDDEF>
<BEGDEF><Alt,><TITLE>less than or equal<TITLE>ó<ENDDEF>
<BEGDEF><Alt.><TITLE>greater than or equal<TITLE>ò<ENDDEF>
