Уровень тревожности (Тейлор)
Tst1 Stnd Tst1 Test.Cfg
Шкала личностной тревоги
Spill Stnd Spill Test.Cfg
Шкала реактивной тревоги
Spilr Stnd Spilr Test.Cfg
Тест-Опросник Стреляу
Ts1 Stnd Ts1 Test.Cfg
Модифицированный тест Лейтеса
Alf Alf1.exe Test.Cfg
Тест-Опросник Кеттела (ф. A)
Ts3 Stnd Ts3 Test.Cfg
Тест-Опросник Кеттела (ф. C)
Ts3c Stnd Ts3c Test.Cfg
Потребность в достижениях
Ts7 Stnd Ts7 Test.Cfg
Mотивация достижений (муж.ф.)
Ts5 Stnd Ts5 Test.Cfg
Мотивация достижений (жен.ф.)
Ts5 Stnd Ts5w Test.Cfg
Mотивация aффиляции
Ts6 Stnd Ts6 Test.Cfg
Тест-Опросник Г.Айзенка: Форма 1
Eysenc1 Stnd Eysenc1 Test.Cfg
Тест-Опросник Г.Айзенка: Форма 2
Eysenc2 Stnd Eysenc2 Test.Cfg
ИСТ-70
IST-70 IST-70.exe Test1.Cfg
IQ (Eysenc) Subtest 1
IQ1 FX.exe IQ Test1 Test.Cfg
Умение работать в коллективе
Tst2 Stnd Tst2 Test.Cfg
Умеете ли вы вести беседу?
Tst3 Stnd Tst3 Test.Cfg
Комплекс угрожаемого авторитета
Tst4 Stnd Tst4 Test.Cfg
Как вы работаете с документацией?
Tst5 Stnd Tst5 Test.Cfg
Проверьте, какой вы руководитель
Tst6 Stnd Tst6 Test.Cfg
Решительны ли Вы?
Tst7 Stnd Tst7 Test.Cfg
Умение вести деловое обсуждение
Tst8 Stnd Tst8 Test.Cfg
Умение вести здоровый образ жизни
Tst9 Stnd Tst9 Test.Cfg
Проверьте свой стиль руководства
Gpl Stnd Gpl Test.Cfg
